import { GameAppState } from "../domain/types";

export const defaultAppState: GameAppState = {
  profile: {
    username: "Billy",
    wallet: {
      connected: false,
      address: null,
    },
    accountXp: 486_250,
    seasonXp: 92_400,
    cryptBalance: 18_750,
    rank: "Silver II",
    dailyStreak: 5,
    weeklyLoginProgress: 5,
    weeklyChestReady: false,
    nftRewardsEarned: 3,
    lastLoginDate: null,
    titles: ["Ashbound Duelist", "Smoke-Blessed", "Vault Initiate"],
    topCards: [
      {
        id: "tcg_1",
        name: "Crypt - Digital Trading Card #1",
        level: 28,
        xp: 46_200,
        mastery: "Ascendant",
        sealedTier: "Sealed Evolution III",
      },
      {
        id: "tcg_90",
        name: "Crypt - Digital Trading Card #90",
        level: 42,
        xp: 73_850,
        mastery: "Sovereign Track",
        sealedTier: "Sealed Evolution III",
      },
      {
        id: "tcg_311",
        name: "Crypt - Digital Trading Card #311",
        level: 12,
        xp: 18_240,
        mastery: "Awakened",
        sealedTier: "Sealed Evolution II",
      },
    ],
    topCommanders: [
      {
        id: "cmd_6600",
        name: "Crypt #6600",
        level: 34,
        xp: 84_500,
        mastery: "Legendary Mastery II",
        title: "The Smoke Sovereign",
      },
      {
        id: "cmd_1",
        name: "Crypt #1",
        level: 19,
        xp: 36_200,
        mastery: "Myth Initiate",
        title: "Ash Reader",
      },
    ],
  },
  dailyQuests: [
    {
      id: "dq_1",
      kind: "daily",
      title: "Play 3 Matches",
      xp: 2_000,
      crypt: 300,
      progress: 2,
      goal: 3,
      claimed: false,
    },
    {
      id: "dq_2",
      kind: "daily",
      title: "Win 2 Matches",
      xp: 2_500,
      crypt: 350,
      progress: 1,
      goal: 2,
      claimed: false,
    },
    {
      id: "dq_3",
      kind: "daily",
      title: "Trigger 3 Exact Matches",
      xp: 3_000,
      crypt: 500,
      progress: 3,
      goal: 3,
      claimed: true,
    },
  ],
  weeklyQuests: [
    {
      id: "wq_1",
      kind: "weekly",
      title: "Log in 7 Days",
      xp: 6_000,
      crypt: 900,
      progress: 5,
      goal: 7,
      claimed: false,
    },
    {
      id: "wq_2",
      kind: "weekly",
      title: "Win 10 Battles",
      xp: 8_000,
      crypt: 1_200,
      progress: 6,
      goal: 10,
      claimed: false,
    },
    {
      id: "wq_3",
      kind: "weekly",
      title: "Play 25 Faction Cards",
      xp: 7_000,
      crypt: 1_000,
      progress: 19,
      goal: 25,
      claimed: false,
    },
  ],
  rewardLedger: [],
  shopItems: [
    {
      id: "shop_quest_reroll",
      name: "Quest Reroll",
      tag: "Utility",
      cost: 750,
      description: "Reroll one daily quest.",
    },
    {
      id: "shop_deck_slot",
      name: "Deck Slot",
      tag: "Account",
      cost: 5_000,
      description: "Unlock an extra saved deck slot.",
    },
    {
      id: "shop_commander_aura",
      name: "Commander Aura Unlock",
      tag: "Prestige",
      cost: 12_500,
      description: "Activate a commander prestige aura.",
    },
    {
      id: "shop_profile_banner",
      name: "Profile Banner Unlock",
      tag: "Profile",
      cost: 8_500,
      description: "Unlock a profile banner tier.",
    },
    {
      id: "shop_seasonal_skin",
      name: "Seasonal Relic Skin",
      tag: "Cosmetic",
      cost: 22_500,
      description: "Unlock a seasonal relic skin.",
    },
    {
      id: "shop_event_entry",
      name: "Event Entry",
      tag: "Competition",
      cost: 3_000,
      description: "Enter a competitive event bracket.",
    },
  ],
};
